### ISSUE TITLE
undefined reference to `hypre_ParCSRMatrixSetColStartsOwner' and `hypre_ParCSRMatrixSetRowStartsOwner'

### ISSUE THREAD

**Issue by MarDiehl** [conda-forge/hypre-feedstock#26]
When building [damask-feedstock](https://github.com/conda-forge/damask-feedstock), CI fails

DAMASK is an Fortran application that uses PETSc.

See the full log at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=366881&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=4392

**Comment by MarDiehl** [comment]
It works for builds on MacOS but still fails for Linux builds

**Comment by dalcinl** [comment]
Your issue is perhaps related to [this changelog entry](https://github.com/hypre-space/hypre/blob/master/CHANGELOG#L15). Looks like in version 2.22 they no longer support `ParCSRMatrixSet{Row|Col}StartsOwner`. Please ask HYPRE upstream for advice.

**Comment by MarDiehl** [comment]
I don't think that these functions have been removed from HYPRE. The current PETSc development branch uses already HYPRE 2.22.1. For some reasons, the same configuration works on MacOS.

This is the full error message
```
/home/conda/feedstock_root/build_artifacts/damask_1629814492406/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/damask_1629814492406/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libpetsc.so: undefined reference to `hypre_ParCSRMatrixSetColStartsOwner'
```

I think the chain of `placehold_` just looks strange but does not cause problems.

Edit: I was to fast: On MacOS, I get an error during runtime:

```
dyld: Symbol not found: _hypre_ParCSRMatrixSetColStartsOwner
```

**Comment by matthiasdiener** [comment]
> I don't think that these functions have been removed from HYPRE. The current PETSc development branch uses already HYPRE 2.22.1. 

But the current PETSc dev branch seems to only use these functions if they are defined: https://gitlab.com/search?search=hypre_ParCSRMatrixSetColStartsOwner&group_id=5422456&project_id=13882401&scope=&search_code=true&snippets=false&repository_ref=main&nav_source=navbar

**Comment by MarDiehl** [comment]
@matthiasdiener many thanks, I've overlooked this
@dalcinl would it make sense to limit HYPRE to <2.22.1 for the current PETSc version?

**Comment by dalcinl** [comment]
Not a HYPRE issue. Closing.
